version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: gestione-rifiuti-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestione_rifiuti
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: gestione-rifiuti-server
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/gestione_rifiuti
      - NODE_ENV=development
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: gestione-rifiuti-client
    depends_on:
      - server
    ports:
      - "4001:80"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data: